# Colors
set -g default-terminal "tmux-256color"

set -g @main_bg 'default'
set -g @module_bg '#313246'
set -g @module_fg '#7db5ff'
set -g @module_current_fg '#181827'
set -g @module_secondary_fg '#9299b4'

# Colors and styles
set -g status-style "bg=#{@main_bg},fg=#{@module_fg}"

# Modules
set -g status-right-length 100
set -g status-left-length 100
# set mode to left status
set -g status-left "\
#[fg=#{@module_current_fg},bg=#{@module_fg},bold] [T|M|U|X] \
#[fg=#{@module_fg},bg=#{@module_bg}]█▓▒░"

# status right: current application / virtual enviroment (if activated) / session name
set -g status-right "\
#[fg=#{@module_bg},bg=#{@main_bg}]░▒▓█\
#[fg=#{@module_fg},bg=#{@module_bg}]#(tmux display-message -p '#{pane_current_command}') \
#[fg=#{@module_fg},bg=#{@module_bg}]░▒▓█\
#[fg=#{@module_current_fg},bg=#{@module_fg},bold]#S"

# window style
set -g window-status-format "\
#[fg=#{@module_secondary_fg},bg=#{@module_bg}]\
#(~/.config/tmux/tmux-window.sh #{window_index} #{session_name})"

# current window style
set -g window-status-current-format "\
#[fg=#{@module_fg},bg=#{@module_bg}]\
#(~/.config/tmux/tmux-current-window.sh #{window_index} #{session_name})"

# window separator
set -g window-status-separator ""

# Mouse On/Off
setw -g mouse on

# Remove Delay
set -g escape-time 1

# Change Repeat Time
set -g repeat-time 1000

# Setting the Window and Panes Index
set -g base-index 1
set -g pane-base-index 1

# Reload Config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Splitting Panes
bind -r _ split-window -v -c "#{pane_current_path}"
bind -r - split-window -h -c "#{pane_current_path}"

# Create New Window
bind c new-window -c "#{pane_current_path}"

# Remapping Movement Keys C-[hjkl] no prefix
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Cycling between panes
bind -r o select-pane -t:.+

# Equal Panes
bind = select-layout main-horizontal
bind + select-layout main-vertical

# Prev & Next Window
bind -r C-h select-window -t:-
bind -r C-l select-window -t:+

# Resizing Panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy Mode
bind -r v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
